

const supportProducts = [
  {
    id: 1,
    name: 'Bestway Cement',
    description: 'A leading cement manufacturer contributing to Pakistan\'s construction industry.',
    impact: 'Supports economic growth through infrastructure development.',
    website: 'https://bestwayconsultancy.com.pk/cement/',
    image: '/assets/support/BWSTWAY-W-1.png',
    tags: ['Cement', 'Fauji Cement'],
  },
  {
    id: 2,
    name: 'Maple Leaf Cement',
    description: 'A prominent cement brand known for high-quality construction materials in Pakistan.',
    impact: 'Enhances infrastructure projects across the nation.',
    website: '#',
    image: '/assets/support/MAPLE-ORDINARY-W.png',
    tags: ['Cement', 'Fauji Cement'],
  },
  {
    id: 3,
    name: 'DG Cement',
    description: 'A leading cement manufacturer in Pakistan, providing innovative and reliable construction solutions.',
    impact: 'Contributes to the development of durable infrastructure.',
    website: 'https://www.dgcement.com/',
    image: '/assets/support/DG-ORDINARY-W-1.png',
    tags: ['Cement', 'Fauji Cement'],
  },
  {
    id: 4,
    name: 'Sarsabz Urea',
    description: 'Organic and locally sourced food products',
    impact: 'Supports sustainable farming and small farmers',
    website: 'https://fatima-group.com/fertilizer/fatima-fertilizer/',
    image: '/assets/support/ssu.png',
    tags: ['DAP', 'Urea', 'CAN', 'NP'],
  },
  {
    id: 5,
    name: 'Engro Urea',
    description: 'Coffee grown and sold by small cooperatives',
    impact: 'Empowers small-scale coffee farmers globally',
    website: 'https://www.engrofertilizers.com/',
    image: '/assets/support/engro-u.png',
    tags: ['Engro DAP', 'Haifa DAP'],
  },
  {
    id: 6,
    name: 'Sarsabz NP',
    description: 'Fresh produce directly from farmers to your table',
    impact: 'Boosts local economy and reduces carbon footprint',
    website: 'https://fatima-group.com/fertilizer/',
    image: '/assets/support/NP-370.png',
    tags: ['DAP', 'Fauji', 'CAN', 'Uria', 'NP'],
  },
  {
    id: 7,
    name: 'Bubber Sher Urea',
    description: 'Books sold by local, independent retailers',
    impact: 'Promotes literacy and supports small businesses',
    website: 'https://fatima-group.com/fertilizer/',
    image: '/assets/support/Urea-Babbar-Shair.png',
    tags: ['DAP', 'Fauji', 'CAN', 'Uria', 'NP'],
  },
  {
    id: 8,
    name: 'Bubber Sher DAP',
    description: 'Affordable renewable energy systems for homes and businesses',
    impact: 'Reduces reliance on fossil fuels and empowers local providers',
    website: 'https://fatima-group.com/fertilizer/',
    image: '/assets/support/DAP-BabbarShair.png',
    tags: ['DAP', 'Fauji', 'CAN', 'Uria', 'NP'],
  },
  {
    id: 9,
    name: 'Vital Urea',
    description: 'Eco-friendly construction supplies for sustainable building',
    impact: 'Encourages green architecture and reduces environmental impact',
    website: 'https://shop.bkk.ag/products/vital-urea-25kg',
    image: '/assets/support/Vital-Urea-2.jpg',
    tags: ['DAP', 'Fauji', 'CAN', 'Uria', 'NP'],
  },
  {
    id: 10,
    name: 'Sarsabz CAN',
    description: 'Affordable healthcare services provided by local clinics',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://fatima-group.com/fertilizer/',
    image: '/assets/support/CAN-370.png',
    tags: ['DAP', 'Fauji', 'CAN', 'Uria', 'NP'],
  },
  {
    id: 11,
    name: 'Asli Milk',
    description: 'Asli Milk is all-purpose full cream milk product by Haleeb Foods.',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://haleebfoods.com/brands/',
    image: '/assets/support/Asli-Packs.png',
    tags: ['Doodh', 'Fauji', 'nurpur', 'Milk'],
  },
  {
    id: 12,
    name: 'Haleeb Full Cream Milk',
    description: 'Haleeb Milk, which is 3.5% full cream UHT milk.',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://haleebfoods.com/brands/',
    image: '/assets/support/Haleeb-packs.png',
    tags: ['Doodh', 'Fauji', 'nurpur', 'Milk'],
  },
  {
    id: 13,
    name: 'Haleeb Butter',
    description: 'Haleeb Butter is a premium product that tastes rich and provides naturally sourced healthy fats for a wholesome life due to its added Vitamins A & D.',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://haleebfoods.com/brands/#butter',
    image: '/assets/support/Butter-1.png',
    tags: ['Butter', 'nurpur', 'Milk', 'Fauji'],
  },
  {
    id: 14,
    name: 'Dairy Cream',
    description: 'Haleeb Dairy Cream has a delicious rich taste. With 30% dairy fat content, the cream is sweet and thick in texture.',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://haleebfoods.com/brands/#cream',
    image: '/assets/support/e82af4961fbfb00eb3a20cf75b40ca30.png',
    tags: ['Cream', 'nurpur', 'Milk', 'Fauji'],
  },
  {
    id: 15,
    name: 'Gourmet Foods',
    description: 'Gourmet Foods is Pakistan\'s largest retail chain of food products with headquarters in Lahore, Pakistan.',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://gourmetfoods.pk/guest',
    image: '/assets/support/gov_logo.png',
    tags: ['Fauji Foods', 'Water', 'Milk', 'Bakery', 'Food and Beverage'],
  },
  {
    id: 16,
    name: 'United Bank Limited (UBL)',
    description: 'UBL\'s Banking service is designed to meet the highest expectations of the clients',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://www.ubldigital.com/',
    image: '/assets/support/ubl.jpg',
    tags: ['Bank', 'Askari Bank', 'Banking', 'FonGrow'],
  },
  {
    id: 17,
    name: 'Leopard Courier',
    description: 'Leopards Courier Services Is The Top-ranked Courier & Logistics Company Providing A One-window Supply Chain Solution.',
    impact: 'Streamlines logistics to improve efficiency and accessibility.',
    website: 'https://www.leopardscourier.com/',
    image: '/assets/support/leopardscourier-logo.png',
    tags: ['Courier', 'Logistics', 'National Logistics Cell'],
  },
  {
    id: 18,
    name: 'Carrefour',
    description: 'Affordable healthcare services provided by local clinics',
    impact: 'Empowers communities by promoting sustainable practices, equitable access to resources, and economic independence for a better future.',
    website: 'https://www.carrefour.pk',
    image: '/assets/support/carrefour.jpg',
    tags: ['food', 'CSD', 'Canteen Stores Department', 'Supermarket', 'Food and Beverage'],
  },
];

export default supportProducts;
